---
title: "02 Main Plots"
format: html
---

```{r}
library(tidyverse)
library(here)
library(glue)
library(jsonlite)
library(patchwork)
library(ggview)

source(here("analysis_scripts", "plot_helpers.R"))

OUTPUT_LOC <- here("outputs")
FIG_LOC <- here("figs")
```

```{r}
full_combined <- readRDS(here(OUTPUT_LOC, "full_combined.rds"))
all_acc <- readRDS(here(OUTPUT_LOC, "all_acc.rds"))
all_human <- readRDS(here(OUTPUT_LOC, "all_human.rds"))
mat_conf_rsa_long <- readRDS(here(OUTPUT_LOC, "rsa_long.rds"))
persev_full <- readRDS(here(OUTPUT_LOC, "persev_full.rds"))
```

# Main feedback plot
```{r}
p_interactive <- full_combined |> 
  filter(feedback == "limited interactive" | is.na(feedback),
         image == "image" | is.na(image),
         condition %in% c("yoked", "backward", "shuffled", "random")) |> 
  make_accuracy_plot() +
  ggtitle("Interactive limited feedback")
```

```{r}
p_humanyoked <- full_combined |> 
  filter(feedback == "limited human-yoked" | is.na(feedback),
         image == "image" | is.na(image),
         condition %in% c("yoked", "backward", "shuffled", "random")) |> 
  make_accuracy_plot() +
  ggtitle("Human-yoked limited feedback")
```

```{r}
p_fullfeedback <- full_combined |> 
  filter(feedback == "full" | is.na(feedback),
         image == "image" | is.na(image),
         condition %in% c("yoked", "backward", "shuffled", "random")) |> 
  make_accuracy_plot() +
  ggtitle("Full feedback")
```

```{r}
p_feedback <- (p_interactive | p_humanyoked | p_fullfeedback) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  coord_cartesian(ylim = c(0, 1)) &
  theme(legend.position = "bottom",
        plot.title = element_text(size = 13, face = "italic"))

(p_feedback + 
  canvas(width = 800, height = 400, 
         scale = 4, units = "px")) |> 
  save_ggplot(here(FIG_LOC, "feedback.png"))
```

# Non-cumulative contexts
```{r}
p_noncumulative <- full_combined |> 
  filter(feedback == "full" | is.na(feedback),
         image == "image" | is.na(image),
         condition %in% c("other-within", "other-across", "ablated", "no context")) |> 
  make_accuracy_plot() +
  COL_SCALE_NOLIM +
  coord_cartesian(ylim = c(0, 1)) +
  ggtitle("Full feedback") +
  theme(plot.title = element_text(size = 13, face = "italic"))

(p_noncumulative + 
  canvas(width = 380, height = 300,
         scale = 4, units = "px")) |> 
  save_ggplot(here(FIG_LOC, "noncumulative.png"))
```

# Learning
```{r}
p_learning <- all_acc |> 
  filter(!is.na(prev_accuracy),
         condition %in% c("yoked", "backward", "shuffled", "random")) |> 
  mutate(target_repNum = target_repNum + 1,
         prev_accuracy = ifelse(prev_accuracy == 1, 
                                "Prev correct", "Prev incorrect")) |> 
  ggplot(aes(x = target_repNum, y = accuracy, 
             col = type)) +
  geom_hline(yintercept = 1 / 12, lty = "dashed") +
  stat_summary(
      aes(group = interaction(gameId, type)),
      fun = mean, geom = "line", alpha = .15,
      show.legend = TRUE
    ) +
  stat_smooth(
    method = "loess", formula = y ~ x, se = FALSE,
    span = .9,
    show.legend = TRUE
  ) +
  stat_summary(
    fun.data = mean_cl_boot, geom = "pointrange",
    lty = "solid",
    show.legend = TRUE
  ) +
  facet_grid(prev_accuracy ~ condition,
             labeller = as_labeller(str_to_sentence)) +
  scale_x_continuous(breaks = 2:6) +
  COL_SCALE +
  labs(
    x = glue("Matcher repetition number"),
    y = "Accuracy", col = "Matcher"
  ) +
  ggtitle("Interactive limited feedback") +
  theme(plot.title = element_text(size = 13, face = "italic"))

(p_learning + 
  canvas(width = 700, height = 320,
         scale = 4, units = "px")) |> 
  save_ggplot(here(FIG_LOC, "learning.png"))
```

# Image vs no image
```{r}
full_image_wide <- full_combined |> 
  rename(image_type = image) |> 
  select(-file_name) |> 
  filter(feedback == "full") |> 
  pivot_wider(names_from = image_type,
              values_from = accuracy) |> 
  mutate(accuracy = image - `no image`)
```

```{r}
p_noimg_diff <- full_image_wide |> 
  make_accuracy_plot(ref_level = 0) +
  COL_SCALE_NOLIM +
  labs(y = "Accuracy difference (image–text − text-only)") +
  coord_cartesian(ylim = c(-0.5, 0.5)) +
  ggtitle("Full feedback") +
  theme(plot.title = element_text(size = 13, face = "italic"))

(p_noimg_diff + 
    canvas(width = 600, height = 320,
           scale = 4, units = "px")) |> 
  save_ggplot(here(FIG_LOC, "noimg_diff.png"))
```

# Human--model correlations
```{r}
yoked_data <- full_combined |> 
  filter(condition == "yoked",
         feedback == "limited interactive" | is.na(feedback),
         image == "image" | is.na(image),
         !str_starts(type, "human_")) |> 
  left_join(full_combined |> 
              filter(condition == "yoked",
                     type == "human_naive") |> 
              rename(orig_acc = accuracy) |> 
              select(-condition, -matcher_trialNum, -matcher_repNum, 
                     -message_length, -context_length, -type),
            by = join_by(gameId, orig_trialNum, orig_repNum, target)) |> 
  mutate(repnum = orig_repNum + 1,
         condition = "yoked")

backward_data <- full_combined |> 
  filter(condition == "backward",
         feedback == "limited interactive" | is.na(feedback),
         image == "image" | is.na(image),
         !str_starts(type, "human_")) |> 
  left_join(full_combined |> 
              filter(condition == "backward",
                     type == "human_naive") |> 
              rename(orig_acc = accuracy) |> 
              select(-condition, -matcher_trialNum, -matcher_repNum, 
                     -message_length, -context_length, -type),
            by = join_by(gameId, orig_trialNum, orig_repNum, target)) |> 
  mutate(repnum = orig_repNum + 1,
         condition = "backward")

shuffled_data <- full_combined |> 
  filter(condition == "shuffled",
         feedback == "limited interactive" | is.na(feedback),
         image == "image" | is.na(image),
         !str_starts(type, "human_")) |> 
  left_join(full_combined |> 
              filter(condition == "shuffled",
                     type == "human_naive") |> 
              rename(orig_acc = accuracy) |> 
              select(-condition, -message_length, -context_length, -type),
            by = join_by(gameId, runId, orig_trialNum, orig_repNum, 
                         matcher_trialNum, matcher_repNum, target)) |> 
  mutate(repnum = orig_repNum + 1) |> 
  group_by(gameId, orig_trialNum, orig_repNum, type) |>
  summarise(
    accuracy = mean(accuracy),
    orig_acc = mean(orig_acc),
    .groups = "drop"
  ) |> 
  mutate(condition = "shuffled")

random_data <- full_combined |> 
  filter(condition == "random",
         feedback == "limited interactive" | is.na(feedback),
         image == "image" | is.na(image),
         !str_starts(type, "human_")) |> 
  left_join(full_combined |> 
              filter(condition == "random",
                     type == "human_naive") |> 
              rename(orig_acc = accuracy) |> 
              select(-condition, -message_length, -context_length, -type),
            by = join_by(gameId, runId, orig_trialNum, orig_repNum, 
                         matcher_trialNum, matcher_repNum, target)) |> 
  mutate(repnum = orig_repNum + 1) |> 
  group_by(gameId, orig_trialNum, orig_repNum, type) |>
  summarise(
    accuracy = mean(accuracy),
    orig_acc = mean(orig_acc),
    .groups = "drop"
  ) |> 
  mutate(condition = "random")

comparison_data <- bind_rows(yoked_data, backward_data, shuffled_data, random_data) |> 
  mutate(type = fct_drop(type),
         condition = factor(condition, levels = c("yoked", "backward", "shuffled", "random")))
```

Correlations
```{r}
comparison_cors <- comparison_data |> 
  group_by(type, condition, gameId, orig_trialNum) |> 
  summarise(
    accuracy = mean(accuracy),
    orig_acc = mean(orig_acc),
    .groups = "drop"
  ) |>
  group_by(type, condition) |> 
  summarise(
    correlation = cor(orig_acc, accuracy, use = "pairwise.complete.obs"),
    spearman = cor(orig_acc, accuracy, method = "spearman", use = "pairwise.complete.obs"),
    .groups = "drop"
  )

cor_text <- comparison_cors |> 
  group_by(condition) |> 
  summarise(
    cor_text = glue(
    'plain(\"model \") * italic(r) %in% \"[{min(correlation) |> strip_zero()}, ',
    '{max(correlation) |> strip_zero()}]\"'),
  )
```

Human split-half
```{r}
workers <- all_human |> 
  distinct(workerid)

sh_cors <- map(1:1000, \(i) {
  set.seed(i)
  
  workers_split <- workers |> 
    mutate(split = sample(1:2, n(), replace = TRUE))
  
  sh_split <- all_human |> 
    left_join(workers_split, by = "workerid") |>
    group_by(condition, split, gameId, orig_trialNum, orig_repNum, 
             correct_tangram) |>
    summarise(accuracy = mean(correct),
              .groups = "drop") |>
    pivot_wider(names_from = split, values_from = accuracy, names_prefix = "split_") |>
    filter(!is.na(split_1) & !is.na(split_2)) |>
    group_by(condition) |> 
    summarise(
      cor = cor(split_1, split_2, use = "pairwise.complete.obs"),
      spearman = cor(split_1, split_2, method = "spearman", use = "pairwise.complete.obs"),
      .groups = "drop"
    ) |> 
    mutate(split = i)
  sh_split
}) |> list_rbind()

sh_cors_sum <- sh_cors |> 
  group_by(condition) |> 
  summarise(
    mean_cor = mean(cor),
    sd_cor = sd(cor),
    median_cor = median(cor),
    ci_lower = quantile(cor, .025),
    ci_upper = quantile(cor, .975),
    .groups = "drop"
  )

sh_sum_text <- sh_cors_sum |> 
  mutate(
    sh_text = glue(
      'plain(\"human \") * italic(r) == \"{mean_cor |> strip_zero()} ',
      '[{ci_lower |> strip_zero()}, {ci_upper |> strip_zero()}]\"')
  ) |> 
  select(condition, sh_text)
```

```{r}
full_cor_text <- cor_text |> 
  left_join(sh_sum_text, by = join_by(condition)) |> 
  mutate(cor_text = glue("atop({cor_text}, {sh_text})")) |> 
  mutate(condition = factor(condition, 
                            levels = c("yoked", "backward", "shuffled", "random")))
```

Plot
```{r}
p_comparison <- comparison_data |> 
  ggplot(aes(x = orig_acc, y = accuracy, col = type)) +
  geom_abline(slope = 1, intercept = 0, lty = "dashed") +
  geom_point(alpha = .06) +
  geom_smooth(method = "lm") +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
  facet_grid(~condition,
             labeller = as_labeller(str_to_sentence)) +
  COL_SCALE_NOLIM +
  labs(
    x = "Naïve human accuracy",
    y = "Model accuracy",
    col = "Matcher"
  ) +
  ggtitle("Interactive limited feedback") +
  theme(legend.position = "bottom",
        legend.box.spacing = unit(0.5, "pt"),
        plot.title = element_text(size = 13, face = "italic"))

(p_comparison + 
    canvas(width = 800, height = 280,
           scale = 4, units = "px")) |> 
  save_ggplot(here(FIG_LOC, "comparison.png"))
```

```{r}
# comparison_plot_text <- p_comparison +
#   geom_label(
#     aes(x = 1, y = 0, label = cor_text),
#     col = "black",
#     data = full_cor_text,
#     parse = TRUE,
#     size = 3,
#     hjust = 1,
#     vjust = 0
#   )
```

# Frontier models
```{r}
p_frontier <- full_combined |> 
  filter(feedback == "frontier" | is.na(feedback),
         image == "image" | is.na(image),
         condition %in% c("yoked", "no context")) |> 
  make_accuracy_plot(repnum_type = "original") +
  COL_SCALE_FRONTIER +
  facet_wrap(~ condition, ncol = 2,
             labeller = as_labeller(str_to_sentence)) +
  ggtitle("Interactive limited feedback") +
  coord_cartesian(ylim = c(0, 1)) +
  guides(col = guide_legend(nrow = 2)) +
  theme(plot.title = element_text(size = 13, face = "italic"),
        legend.position = "bottom")

(p_frontier + 
  canvas(width = 450, height = 300,
         scale = 4, units = "px")) |> 
  save_ggplot(here(FIG_LOC, "frontier.png"))
```

# Original order
```{r}
p_original <- full_combined |> 
  filter(feedback == "full" | is.na(feedback),
         image == "image" | is.na(image),
         condition %in% c("shuffled", "backward", "random", "no context")) |> 
  make_accuracy_plot(repnum_type = "original") +
  COL_SCALE_NOLIM +
  ggtitle("Full feedback") +
  theme(plot.title = element_text(size = 13, face = "italic"))

(p_original + 
  canvas(width = 380, height = 300,
         scale = 4, units = "px")) |> 
  save_ggplot(here(FIG_LOC, "original.png"))
```

# Item-wise variation
```{r}
p_items <- full_combined |> 
  filter(feedback == "limited interactive" | is.na(feedback),
         image == "image" | is.na(image)) |> 
  mutate(target = fct_reorder(target, accuracy, .na_rm = TRUE)) |>
  ggplot(aes(x = target, y = accuracy, col = type)) +
  geom_hline(yintercept = 1 / 12, lty = "dashed") +
  stat_summary(
      aes(group = interaction(gameId, type, target)),
      fun = mean, geom = "point", alpha = .2,
      position = position_jitter(width = .2)
    ) +
  stat_summary(fun.data = mean_cl_boot, 
               geom = "pointrange", size = .4,
               position = position_dodge(width = .2)) +
  facet_wrap(~condition, nrow = 2,
             labeller = as_labeller(str_to_sentence)) +
  COL_SCALE +
  labs(x = "Tangram", y = "Accuracy", col = "Matcher") +
  ggtitle("Interactive limited feedback") +
  theme(plot.title = element_text(size = 13, face = "italic"))

(p_items +
    canvas(width = 420, height = 300,
         scale = 4, units = "px")) |> 
  save_ggplot(here(FIG_LOC, "items.png"))
```

# Confusion matrices
```{r}
p_rsa <- mat_conf_rsa_long |> 
  mutate(type = case_when(
           type == "model_gemma" ~ "Gemma 3",
           type == "model_qwen" ~ "Qwen 2.5 VL",
           type == "model_llama" ~ "Llama 3.2",
           type == "model_molmo" ~ "Molmo 2",
           type == "model_kimi" ~ "Kimi VL"
         ) |> factor(levels = c("Qwen 2.5 VL", "Gemma 3", "Llama 3.2", 
                                "Molmo 2", "Kimi VL"))) |>
  ggplot(aes(x = condition2, y = condition1, fill = cor)) +
  geom_tile() +
  facet_grid(~type) +
  scale_fill_gradient(low = "white", high = "#7212b3", limits = c(0, 1)) +
  labs(x = "", y = "", fill = "Correlation") +
  theme(axis.text.x = element_text(hjust = 1, angle = 45)) +
  ggtitle("Full feedback") +
  theme(plot.title = element_text(size = 13, face = "italic"))

(p_rsa +
    canvas(width = 1000, height = 290,
         scale = 4, units = "px")) |> 
  save_ggplot(here(FIG_LOC, "rsa.png"))
```

# Practice 
```{r}
p_practice <- full_combined |> 
  filter(str_detect(condition, "practice")) |> 
  make_accuracy_plot() +
  COL_SCALE_NOLIM +
  facet_wrap(~ condition, ncol = 2,
             labeller = as_labeller(str_to_sentence)) +
  coord_cartesian(ylim = c(0, 1))
```

```{r}
p_persev <- persev_full |> 
  rename(accuracy = is_same,
         matcher_trialNum = matcher_trialNum.x) |> 
  mutate(type = factor(type, 
                       levels = c("model_qwen", "model_gemma", 
                                  "model_llama", "model_molmo", "model_kimi"))) |> 
  make_accuracy_plot() +
  COL_SCALE_NOLIM +
  facet_wrap(~ condition, ncol = 2,
             labeller = as_labeller(str_to_sentence)) +
  coord_cartesian(ylim = c(0, 1),
                  xlim = c(1, 6)) +
  labs(y = "Perseveration")
```

```{r}
p_prac_pers <- (p_practice / p_persev) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A",
                  title = "Interactive limited feedback",
                  theme = theme(plot.title = 
                                  element_text(size = 13, face = "italic")))

(p_prac_pers + 
  canvas(width = 450, height = 400,
         scale = 4, units = "px")) |> 
  save_ggplot(here(FIG_LOC, "practice.png"))
```

